### ISSUE TITLE
Failed to connect to AE

### ISSUE THREAD

**Issue by anfalk462** [google/AEUX#144]
With the latest update to After Effects, AEUX is failing to connect to AE. Anyone else getting this?

**Comment by designelf** [comment]
This is happening to me as well. I've re-installed v0.8.1-b and still no luck

**Comment by trounceabout** [comment]
Same issue happening here as well

**Comment by samcreate** [comment]
Same here. Once adobe automatically installed IAE 22.6.0 I get the "Failed to connect to AE" error in Figma, but when I open Figma's console, I see this error: 

```
POST http://127.0.0.1:7240/evalScript 500 (Internal Server Error)
onmessage @ VM985:22
postMessage (async)
postMessage @ figma_app.min.js.br:802
await in postMessage (async)
postMessageToIframe @ figma_app.min.js.br:701
(anonymous) @ figma_app.min.js.br:919
(anonymous) @ figma_app.min.js.br:896
Z0d.t.invokeCallback @ figma_app.min.js.br:582
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm:0x59d8
$func138 @ jsvm-cpp.wasm:0x136e3
$func147 @ jsvm-cpp.wasm:0x152eb
$func147 @ jsvm-cpp.wasm:0x17216
$func294 @ jsvm-cpp.wasm:0x33c57
$jsvm_callFunction @ jsvm-cpp.wasm:0xaecb
callFunction @ figma_app.min.js.br:582
callFunction @ figma_app.min.js.br:611
iframeMessageHandler @ figma_app.min.js.br:918
IVr.toplevelWindowMessageChannel.port2.onmessage @ figma_app.min.js.br:792
VM985:22 Error: failed to connect
    at <anonymous>:22:170953
```

**Comment by pedrorodrigoalves** [comment]
yep same problem here, tried reinstalling everything and liberating security access, but no changes

**Comment by msongz** [comment]
@adamplouff please take a look

**Comment by PeterDickinson** [comment]
When can we expect a resolve for this? Such a key aspect to workflow now :)

**Comment by haxxeren1** [comment]
Similar problems here! After updating Ae to 22.6.0, importing frames from Figma became impossible for me.
P.S I have the latest AEUX version 0.8.1-b and tried to reinstall both plugins, still doesn't work

<img width="176" alt="Screen Shot 2022-08-31 at 7 26 57 PM" src="https://user-images.githubusercontent.com/112598674/187819190-47f7b07e-0b92-411b-91b9-23f43e498c59.png">

**Comment by adamplouff** [comment]
@anfalk462 @designelf @mmaksym17 @trounceabout @samcreate @sertanarig @pedrorodrigoalves @msongz @PeterDickinson @haxxeren1 

I think it's fixed in this build. Should just need to install the Ae panel.

https://github.com/google/AEUX/releases/download/v0.8.2/AEUX_0.8.2.zip

**Comment by mimosav** [comment]
I'm still experiencing this same issue despite updating everything, and restarting all programs/laptop a few times.. should I delete the old version, or could clicking 'reset preferences' from the ZXP installer window help?

**Comment by t-michaela** [comment]
I upgraded to 0.8.2, and am having this issue still.

To test a simple example, I tried exporting a red artboard (named "Frame 2"), and received a `POST http://127.0.0.1:7240/evalScript 500 (Internal Server Error)`


This is a copy-paste of the payload from the failed `writeFiles` request (which also had a 500 error):

```
{"switch":"aftereffects","images":[{"name":"Frame 2_13-2438.png","imgData":"iVBORw0KGgoAAAANSUhEUgAAA7QAAAVVCAYAAAArD4ezAAAACXBIWXMAACE4AAAhOAFFljFgAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAB90SURBVHgB7dcBCcAwEMDA35iB+hf7q43AHUREnj1nBwAAAFr2HQAAAAgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAABiKDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAgydACAACQZGgBAABIMrQAAAAkGVoAAACSDC0AAABJhhYAAIAkQwsAAECSoQUAACDJ0AIAAJBkaAEAAEgytAAAACQZWgAAAJIMLQAAAEmGFgAAgCRDCwAAQJKhBQAAIMnQAgAAkGRoAQAASDK0AAAAJBlaAAAAkgwtAAAASYYWAACAJEMLAABAkqEFAAAg6bvtAAAAQMv+lIgPySyqSVoAAAAASUVORK5CYII="}],"data":{"layerData":[{"type":"Artboard","aeuxVersion":0.81,"hostApp":"Figma","name":"Frame 2","bgColor":[0.9999999403953552,0.06666678190231323,0.0666671171784401,1],"size":[316,455],"layerCount":0,"rasterizeList":[]},{"type":"Image","name":"Frame 2","id":"13-2438","frame":{"x":158,"y":227.5,"width":316,"height":455},"isVisible":true,"opacity":50,"blendMode":"BlendingMode.NORMAL","isMask":false,"rotation":0,"guide":true}]}}
```


Likewise, this is the payload from the failed `evalScript` request:
```
{"method":"buildLayers","data":{"layerData":[{"type":"Artboard","aeuxVersion":0.81,"hostApp":"Figma","name":"Frame 2","bgColor":[0.9999999403953552,0.06666678190231323,0.0666671171784401,1],"size":[316,455],"layerCount":0,"rasterizeList":[]}]},"switch":"aftereffects","getPrefs":true}
```

I wish I could be helpful and debug this on my own 😅

**Comment by charlesscheuer** [comment]
I also can't connect on 0.8.1-b :(

**Comment by Linhaolong** [comment]
You must open the AE softwar and click this figma plus button,it can work

**Comment by TXTNT404** [comment]
3Q @adamplouff

**Comment by deraalex** [comment]
just freshly installed the AE Plugin and the Figma Plugin via manifest.js
restarted everything but always geht the message "failed to connect to ae"
aeux in ae is version v0.8.2. but aeux figma is version v0.8.1-b
